print("---------------------------------------------------------------")
print("Converting number into binary")
print("The binary value of 111 is:", bin(111))
print("Converting binary 11001 into decimal we get :", 0b11001)

print("---------------------------------------------------------------")
print("Converting number into octal")
print("The octal value of 111 is:", oct(111))
print("Converting octal 1016 into decimal we get :", 0o1016)
print("---------------------------------------------------------------")
print("Converting number into binary")
print("The Hex value of 111 is:", hex(111))
print("Converting Hex 15A into decimal we get :", 0x15A)
print("---------------------------------------------------------------")
